### ISSUE TITLE
1.16.5 forge Invisibility Blindness not permanent

### ISSUE THREAD

**Issue by NighthowlerStudios** [capnkirok/betterinvisibility#1]
the blindness goes away instantly.  this throws off pvp balance when using mr crayfish guns (or any projectile weapon for that matter)

if you can't do this fix, could you possibly add ranged weapons such as  mr crayfish's guns?

using Kaleidio's Battle Pack at the time

**Comment by capnkirok** [comment]
Huh, what? Can you provide me with more context? The blindness should remain active as long as you have an invisibility potion active. It would turn off if it was removed by another mod (or there is another conflict).

Can you explain to me what weapon you are using and what exactly is happening in more detail? It may have to be a fix on Mr Crayfish's side, but I can take a look.

**Comment by NighthowlerStudios** [comment]
look, all I can tell you is that when I would drink a potion of invisibility, the Blindness I wanted active would last only like a few ticks.  the log would spit no errors.  it just wouldn't function.

**Comment by NighthowlerStudios** [comment]
you can install Kaleidio's Battle Pack 3.3.2 from curseforge yourself to test and find this to be reproducible 100%

**Comment by capnkirok** [comment]
Well, it's nothing to do with the Battle Pack. Just a bad line of code in 1.16. Will update soon.

**Comment by NighthowlerStudios** [comment]
I thought so!  Thanks a bunch

and do you think you could add support like some sort of config for more weapons to trigger the "reveal"?

**Comment by NighthowlerStudios** [comment]
Hey there, you haven't released this milestone to curse. Something wrong?  Closing since you have it fixed on the git

**Comment by capnkirok** [comment]
It's only fixed in development, so can call it closed until I release. Trying to fix something else before I release.

**Comment by NighthowlerStudios** [comment]
Ah alright.

**Comment by NighthowlerStudios** [comment]
It's been another month and still nothing has been released.
