### ISSUE TITLE
Does not hide Armor in Multiplayer

### ISSUE THREAD

**Issue by Slimik222** [capnkirok/betterinvisibility#3]
screenshots from the game
![2021-09-28_3](https://user-images.githubusercontent.com/91560161/135135210-c0db9172-e925-4492-8ed4-0f385470c9d8.png)
![2021-09-28_18 31 37](https://user-images.githubusercontent.com/91560161/135135241-e702e61c-c087-4eab-a913-dc4ebc90d3f0.png)
![2021-09-28](https://user-images.githubusercontent.com/91560161/135135246-63040aa9-81c1-4f42-a022-e40165a917d8.png)
![2021-09-28_18 31 46](https://user-images.githubusercontent.com/91560161/135135255-e229664f-9071-4ab7-85ae-2b01bb6bb3d7.png)

**Comment by capnkirok** [comment]
Thank you for the screenshots. Looks like you are using 1.16.5. Do you have any other mods installed? If so, can you share?

**Comment by Slimik222** [comment]
okay later I will send all mods, now the computer is not available

**Comment by Slimik222** [comment]
We tried without mods
armor visible

**Comment by capnkirok** [comment]
I'll do some multiplayer testing and get back to you.

**Comment by capnkirok** [comment]
This is confirmed bug. Armor still showing in multiplayer. Working on fix now.

**Comment by capnkirok** [comment]
Ok, I finally figured this out. The Client side is not aware of the active effects of other players, only itself, so Client side continued to render the layers of other players. At any rate, fixed and will be uploaded shortly.
