### ISSUE TITLE
[Critical] [1.16] Crash-Report - Mobticking?

### ISSUE THREAD

**Issue by Cixon** [capnkirok/betterinvisibility#4]
Initially this was reported to a different mod but it appears upon further investigation the crash is caused by BetterInvisiblity.

Issue:
https://github.com/someaddons/dungeonbosses/issues/16

Logs:
https://gist.github.com/Cixon/ac4d7e866fc48acd550d220f6c37f0cf

**Comment by capnkirok** [comment]
Yep. My bug. Will issue an update soon.

**Comment by Cixon** [comment]
excellent, thank you!

**Comment by capnkirok** [comment]
Ok, fixed in Dev. Should be up later today.
