### ISSUE TITLE
Crash with Twilight Forest

### ISSUE THREAD

**Issue by ghost** [capnkirok/betterinvisibility#5]
https://pastebin.ubuntu.com/p/CzVxmMyY8G/

**Comment by ghost** [comment]
Another crash with IAF

https://pastebin.ubuntu.com/p/YY836wnp4h/

**Comment by capnkirok** [comment]
Top one is already noted and in progress. Second one is new. Will require some investigation.

**Comment by capnkirok** [comment]
Alright, these are fixed in Dev. Gonna do a best of testing, then release.
