### ISSUE TITLE
1.16.5 1.0.3 Config file not working

### ISSUE THREAD

**Issue by thicc-penguin** [capnkirok/betterinvisibility#8]
I'm using 1.0.3 on our server and use the mod to make invisibility useful in combat with mobs. However, to balance it for PVP we decided it would be best to show armor, but setting "showArmorWeapons = true" in the config still does not render the armor and weapons.

The rest of the config works perfectly fine!

**Comment by capnkirok** [comment]
Yep, it's a bug! I've fixed it in my dev environment. Next version should be up later today.
